# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

ignore:
  - "example/"
  - "src/test/"

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: yes
      method: no
      macro: no

coverage:
  range: 50..100
  status:
    project:
      default:
        target: auto
        threshold: 1.0%
        branches: null

    patch:
      default:
        target: auto
        branches: null


