# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - protobuf-compiler
  jobs:
    pre_build:
      - cd docs && doxygen
      - wget -c https://github.com/pseudomuto/protoc-gen-doc/releases/download/v1.5.1/protoc-gen-doc_1.5.1_linux_amd64.tar.gz -O - | tar -xz
      - mkdir -p docs/protodoc
      - cd src/resources && protoc --plugin=protoc-gen-doc=../../protoc-gen-doc --doc_out=../../docs/protodoc --doc_opt=../../docs/protodoc.tmpl,proto.md *proto
      - cd dependencies && git clone --no-single-branch --depth 50 https://github.com/GenomicsDB/GenomicsDB-Python.git .
      - mv GenomicsDB-Python/genomicsdb GenomicsDB-Python/genomicsdb_data
      - pip install genomicsdb

formats:
  - pdf

python:
    install:
      - requirements: docs/requirements.txt
