# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - cd docs && doxygen
      - ls docs/ && ls docs/doxydocs && ls docs/doxyrst

formats:
  - pdf

python:
    install:
      - requirements: docs/requirements.txt
