# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - openjdk-11-jdk
    - protobuf-compiler
    - maven
  jobs:
    post_build:
      - mvn javadoc:javadoc -Dprotoc.filepath=/usr/bin/protoc -Dgenomicsdb_source_directory=$(pwd)
      - mkdir -p docs/_static/
      - mv build/site/apidocs docs/_static/javadocs

formats:
  - pdf

python:
    install:
      - requirements: docs/requirements.txt
