# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - openjdk-11-jdk
    - protobuf-compiler
    - maven
  commands:
    - python -mvirtualenv env
    - env/bin/python -m pip install --upgrade --no-cache-dir jinja2<3.1.0
    - env/bin/python -m pip install -r docs/requirements.txt
    - echo $SHELL
    - . env/bin/activate && cd docs && make html && cd ..
    - mvn javadoc:javadoc -Dprotoc.filepath=/usr/bin/protoc -Dgenomicsdb_source_directory=$(pwd)
    - mv build/site/apidocs/* docs/_build/html/javadocs
    - mkdir _readthedocs/ && mv docs/_build/html _readthedocs/
#    - env/bin/python -m pip install --upgrade --no-cache-dir pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<2.3 jinja2<3.1.0
#  jobs:
#    post_build:
#      - mvn javadoc:javadoc -Dprotoc.filepath=/usr/bin/protoc -Dgenomicsdb_source_directory=$(pwd)
#      - ls docs/_build/html
#      - mv build/site/apidocs/* docs/_build/html/javadocs
#      - ls docs/_build/html
#      - ls docs/_build/html/javadocs

formats:
  - pdf

python:
    install:
      - requirements: docs/requirements.txt
