# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

coverage:
  range: 50..100
  status:
    project:
      default:
        target: auto
        threshold: 1.0%
        branches: null

    patch:
      default:
        target: auto
        branches: null


