# The MIT License (MIT)
# Copyright (c) 2022 Omics Data Automation, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Description: Docker file to generate GenomicsDB release jar

FROM ghcr.io/genomicsdb/genomicsdb:centos_6_prereqs
ARG GENOMICSDB_RELEASE_VERSION=""
ARG MAC_DYLIB_PATH=""
ARG USE_HDFS=""

ENV DOCKER_BUILD=true
ENV MAC_DYLIB_PATH=${MAC_DYLIB_PATH}
ENV USE_HDFS=${USE_HDFS}
ENV GENOMICSDB_RELEASE_VERSION=${GENOMICSDB_RELEASE_VERSION}
COPY . /build/GenomicsDB/
COPY libtiledbgenomicsdb.dylib ${MAC_DYLIB_PATH}
WORKDIR /build/GenomicsDB
RUN useradd -r -U -m genomicsdb &&\
    ./scripts/install_genomicsdb.sh genomicsdb /usr/local true java
    