include(CheckCXXCompilerFlag)
#Check C++ Compiler Support
macro (CHECK_AND_SET_STD_CXX_2011_FLAG CXX_STD_2011_FOUND)
  if(BUILD_NANOARROW)
    #std::binary_semaphore requires C++ 2020
    #set(CMAKE_CXX_FLAGS "${BACKUP_CMAKE_CXX_FLAGS} -std=c++20")
    CHECK_CXX_COMPILER_FLAG(-std=c++20 ${CXX_STD_2011_FOUND})
    if(${CXX_STD_2011_FOUND})
      set(CMAKE_CXX_STANDARD 20)
    endif()
  else()
    #string_view requires C++ 2017 support - most compilers that
    #support string_view also support 2017 (or 201y)
    #set(CMAKE_CXX_FLAGS "${BACKUP_CMAKE_CXX_FLAGS} -std=c++17")
    CHECK_CXX_COMPILER_FLAG(-std=c++17 ${CXX_STD_2011_FOUND})
    if(${CXX_STD_2011_FOUND})
      set(CMAKE_CXX_STANDARD 17)
    endif()
  endif()
  if(NOT ${CXX_STD_2011_FOUND})
    message(WARNING "Need at least C++17 for compiling source as is, but it can be modified easily to make it C++11 compliant")
    set(BACKUP_CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    set(CMAKE_CXX_FLAGS "${BACKUP_CMAKE_CXX_FLAGS} -std=c++1y")
    CHECK_CXX_COMPILER_FLAG(-std=c++1y ${CXX_STD_2011_FOUND})
    if(NOT ${CXX_STD_2011_FOUND})
      set(CMAKE_CXX_FLAGS "${BACKUP_CMAKE_CXX_FLAGS} -std=c++11")
      CHECK_CXX_COMPILER_FLAG(-std=c++11 ${CXX_STD_2011_FOUND})
      if(NOT ${CXX_STD_2011_FOUND})
	set(CMAKE_CXX_FLAGS "${BACKUP_CMAKE_CXX_FLAGS}")
      endif()
    endif()
  endif()
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
  set(CMAKE_CXX_EXTENSIONS OFF)
endmacro()
