# from: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Create and publish a Docker image

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.rst'
    branches:
      - develop
    tags:
      - v*
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.rst'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and export to Docker
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: os=ubuntu:jammy
          load: true
          tags: ghcr.io/genomicsdb/genomicsdb:test

      - name: Test docker image
        run: |
          docker run --rm -v ${{github.workspace}}/tests:/opt/tests --entrypoint /opt/tests/docker_test.sh ghcr.io/genomicsdb/genomicsdb:test

      - name: Build and push to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: os=ubuntu:jammy
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
